require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoringOldRailsTasksController do

  # This should return the minimal set of attributes required to create a valid
  # BoringOldRailsTask. As you add validations to BoringOldRailsTask, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all boring_old_rails_tasks as @boring_old_rails_tasks" do
      boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
      get :index
      assigns(:boring_old_rails_tasks).should eq([boring_old_rails_task])
    end
  end

  describe "GET show" do
    it "assigns the requested boring_old_rails_task as @boring_old_rails_task" do
      boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
      get :show, :id => boring_old_rails_task.id
      assigns(:boring_old_rails_task).should eq(boring_old_rails_task)
    end
  end

  describe "GET new" do
    it "assigns a new boring_old_rails_task as @boring_old_rails_task" do
      get :new
      assigns(:boring_old_rails_task).should be_a_new(BoringOldRailsTask)
    end
  end

  describe "GET edit" do
    it "assigns the requested boring_old_rails_task as @boring_old_rails_task" do
      boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
      get :edit, :id => boring_old_rails_task.id
      assigns(:boring_old_rails_task).should eq(boring_old_rails_task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BoringOldRailsTask" do
        expect {
          post :create, :boring_old_rails_task => valid_attributes
        }.to change(BoringOldRailsTask, :count).by(1)
      end

      it "assigns a newly created boring_old_rails_task as @boring_old_rails_task" do
        post :create, :boring_old_rails_task => valid_attributes
        assigns(:boring_old_rails_task).should be_a(BoringOldRailsTask)
        assigns(:boring_old_rails_task).should be_persisted
      end

      it "redirects to the created boring_old_rails_task" do
        post :create, :boring_old_rails_task => valid_attributes
        response.should redirect_to(BoringOldRailsTask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boring_old_rails_task as @boring_old_rails_task" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoringOldRailsTask.any_instance.stub(:save).and_return(false)
        post :create, :boring_old_rails_task => {}
        assigns(:boring_old_rails_task).should be_a_new(BoringOldRailsTask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BoringOldRailsTask.any_instance.stub(:save).and_return(false)
        post :create, :boring_old_rails_task => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boring_old_rails_task" do
        boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
        # Assuming there are no other boring_old_rails_tasks in the database, this
        # specifies that the BoringOldRailsTask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BoringOldRailsTask.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => boring_old_rails_task.id, :boring_old_rails_task => {'these' => 'params'}
      end

      it "assigns the requested boring_old_rails_task as @boring_old_rails_task" do
        boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
        put :update, :id => boring_old_rails_task.id, :boring_old_rails_task => valid_attributes
        assigns(:boring_old_rails_task).should eq(boring_old_rails_task)
      end

      it "redirects to the boring_old_rails_task" do
        boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
        put :update, :id => boring_old_rails_task.id, :boring_old_rails_task => valid_attributes
        response.should redirect_to(boring_old_rails_task)
      end
    end

    describe "with invalid params" do
      it "assigns the boring_old_rails_task as @boring_old_rails_task" do
        boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BoringOldRailsTask.any_instance.stub(:save).and_return(false)
        put :update, :id => boring_old_rails_task.id, :boring_old_rails_task => {}
        assigns(:boring_old_rails_task).should eq(boring_old_rails_task)
      end

      it "re-renders the 'edit' template" do
        boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BoringOldRailsTask.any_instance.stub(:save).and_return(false)
        put :update, :id => boring_old_rails_task.id, :boring_old_rails_task => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boring_old_rails_task" do
      boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
      expect {
        delete :destroy, :id => boring_old_rails_task.id
      }.to change(BoringOldRailsTask, :count).by(-1)
    end

    it "redirects to the boring_old_rails_tasks list" do
      boring_old_rails_task = BoringOldRailsTask.create! valid_attributes
      delete :destroy, :id => boring_old_rails_task.id
      response.should redirect_to(boring_old_rails_tasks_url)
    end
  end

end
